require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MetalinksController do

  # This should return the minimal set of attributes required to create a valid
  # Metalink. As you add validations to Metalink, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "metafile_from_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MetalinksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all metalinks as @metalinks" do
      metalink = Metalink.create! valid_attributes
      get :index, {}, valid_session
      assigns(:metalinks).should eq([metalink])
    end
  end

  describe "GET show" do
    it "assigns the requested metalink as @metalink" do
      metalink = Metalink.create! valid_attributes
      get :show, {:id => metalink.to_param}, valid_session
      assigns(:metalink).should eq(metalink)
    end
  end

  describe "GET new" do
    it "assigns a new metalink as @metalink" do
      get :new, {}, valid_session
      assigns(:metalink).should be_a_new(Metalink)
    end
  end

  describe "GET edit" do
    it "assigns the requested metalink as @metalink" do
      metalink = Metalink.create! valid_attributes
      get :edit, {:id => metalink.to_param}, valid_session
      assigns(:metalink).should eq(metalink)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Metalink" do
        expect {
          post :create, {:metalink => valid_attributes}, valid_session
        }.to change(Metalink, :count).by(1)
      end

      it "assigns a newly created metalink as @metalink" do
        post :create, {:metalink => valid_attributes}, valid_session
        assigns(:metalink).should be_a(Metalink)
        assigns(:metalink).should be_persisted
      end

      it "redirects to the created metalink" do
        post :create, {:metalink => valid_attributes}, valid_session
        response.should redirect_to(Metalink.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved metalink as @metalink" do
        # Trigger the behavior that occurs when invalid params are submitted
        Metalink.any_instance.stub(:save).and_return(false)
        post :create, {:metalink => { "metafile_from_id" => "invalid value" }}, valid_session
        assigns(:metalink).should be_a_new(Metalink)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Metalink.any_instance.stub(:save).and_return(false)
        post :create, {:metalink => { "metafile_from_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested metalink" do
        metalink = Metalink.create! valid_attributes
        # Assuming there are no other metalinks in the database, this
        # specifies that the Metalink created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Metalink.any_instance.should_receive(:update).with({ "metafile_from_id" => "1" })
        put :update, {:id => metalink.to_param, :metalink => { "metafile_from_id" => "1" }}, valid_session
      end

      it "assigns the requested metalink as @metalink" do
        metalink = Metalink.create! valid_attributes
        put :update, {:id => metalink.to_param, :metalink => valid_attributes}, valid_session
        assigns(:metalink).should eq(metalink)
      end

      it "redirects to the metalink" do
        metalink = Metalink.create! valid_attributes
        put :update, {:id => metalink.to_param, :metalink => valid_attributes}, valid_session
        response.should redirect_to(metalink)
      end
    end

    describe "with invalid params" do
      it "assigns the metalink as @metalink" do
        metalink = Metalink.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Metalink.any_instance.stub(:save).and_return(false)
        put :update, {:id => metalink.to_param, :metalink => { "metafile_from_id" => "invalid value" }}, valid_session
        assigns(:metalink).should eq(metalink)
      end

      it "re-renders the 'edit' template" do
        metalink = Metalink.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Metalink.any_instance.stub(:save).and_return(false)
        put :update, {:id => metalink.to_param, :metalink => { "metafile_from_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested metalink" do
      metalink = Metalink.create! valid_attributes
      expect {
        delete :destroy, {:id => metalink.to_param}, valid_session
      }.to change(Metalink, :count).by(-1)
    end

    it "redirects to the metalinks list" do
      metalink = Metalink.create! valid_attributes
      delete :destroy, {:id => metalink.to_param}, valid_session
      response.should redirect_to(metalinks_url)
    end
  end

end
